export const Users = [
  {
    id: 1,
    profilePicture: "assets/person/1.jpeg",
    username: "Debra Meng",
  },
  {
    id: 2,
    profilePicture: "assets/person/2.jpeg",
    username: "Tyler Durden",
  },
  {
    id: 3,
    profilePicture: "assets/person/3.jpeg",
    username: "Mariel Blomfeld",
  },
  {
    id: 4,
    profilePicture: "assets/person/4.jpeg",
    username: "Carrianne Hawkins",
  },
  {
    id: 5,
    profilePicture: "assets/person/5.jpeg",
    username: "Francesa Bardson",
  },
  {
    id: 6,
    profilePicture: "assets/person/6.jpeg",
    username: "Shireen Desjarlais",
  },
  {
    id: 7,
    profilePicture: "assets/person/7.jpeg",
    username: "Pete Cardin",
  },
  {
    id: 8,
    profilePicture: "assets/person/8.jpeg",
    username: "Karen Hildebrand",
  },
  {
    id: 9,
    profilePicture: "assets/person/9.jpeg",
    username: "Jaqueesha Hicks",
  },
  {
    id: 10,
    profilePicture: "assets/person/10.jpeg",
    username: "Ember Moon",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love is All.",
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "assets/post/2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/post/3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    desc: "Wow!",
    photo: "assets/post/4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    desc: "No words...",
    photo: "assets/post/5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    desc: "Tuna please!",
    photo: "assets/post/6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assets/post/7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    desc: "Be the change you want to see...",
    photo: "assets/post/8.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "assets/post/9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    desc: "Ideas can change the world.",
    photo: "assets/post/10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
